services:
  web_server:
    build: .
    container_name: respi-webserver
    ports:
      - "${WEB_SERVER_PORT}:3000"
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - .:/web
    depends_on:
      - database
    environment:
      - TZ=Europe/Madrid
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    restart: unless-stopped

  database:
    image: yobasystems/alpine-mariadb:11.4.5
    container_name: respi-db
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Europe/Madrid
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: respi-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - database
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
